name: Enforce Tag Naming Conventions

on:
  push:
    tags:
      - 'v[1-3]*'

jobs:
  validate-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Validate Tag Name
        run: |
          TAG_NAME=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')
          if [[ ! $TAG_NAME =~ ^v[1-3] ]]; then
            echo "Tag name $TAG_NAME does not match the required pattern v1*, v2*, v3*"
            exit 1
          fi

      - name: Notify Maintainers
        if: failure()
        run: |
          echo "Tag naming validation failed for $TAG_NAME. Please follow the naming convention v1*, v2*, v3*."
